#!/bin/bash

INSTALL_PREFIX=/usr/local

chmod 555 ${INSTALL_PREFIX}/bin/pdip
chown root ${INSTALL_PREFIX}/bin/pdip
chgrp root ${INSTALL_PREFIX}/bin/pdip
chmod 444 ${INSTALL_PREFIX}/share/man/fr/man1/pdip.1.gz
chown root ${INSTALL_PREFIX}/share/man/fr/man1/pdip.1.gz
chgrp root ${INSTALL_PREFIX}/share/man/fr/man1/pdip.1.gz
chmod 444 ${INSTALL_PREFIX}/share/man/man1/pdip.1.gz
chown root ${INSTALL_PREFIX}/share/man/man1/pdip.1.gz
chgrp root ${INSTALL_PREFIX}/share/man/man1/pdip.1.gz
